name: Daily Weather Alert

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  weather-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests python-dotenv

      - name: Run Script
        env:
          SMTP_ID: ${{ secrets.SMTP_ID }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          FROM_ADDR: ${{ secrets.FROM_ADDR }}
          TO_ADDR: ${{ secrets.TO_ADDR }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: python main.py
